# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tomoya
brief-intro: Code, Animation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomoya92.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
#twitter_username:
#facebook_username:
github_username:  tomoya92
email: py2qiuse@gmail.com
weibo_username: liygheart
zhihu_username: liygheart
#linkedIn_username:
#dribbble_username:

description_footer: Hello World!

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: tomoya92
disqus_shortname: tomoya

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: ebcdac2d132aa663e3ee4c53656bad25
#google_analytics_id:

# Build settings
markdown: kramdown

kramdown:
  extensions:
    - autolink
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      true
  footnote_nr:    1

highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
